Repository yatima-inc/yatima, pull requests merged in 2022-08, with the labels that each got.

#146 Optimize test infra
  Fixtures/AnonCidGroups/Definitions.lean
  Fixtures/AnonCidGroups/PartialDefinitions.lean
  Fixtures/AnonCidGroups/UnsafeDefinitions.lean
  Tests/AnonCidGroups.lean
  Tests/AnonCidGroups/Definitions.lean
  Tests/AnonCidGroups/Inductives.lean
  Tests/AnonCidGroups/ToImport.lean
  Tests/FromIpld.lean
  Tests/Termination.lean
  Tests/Termination/NastyInductives.lean
  Tests/Termination/Prelude.lean
  TestsUtils/CompileAndExtractTests.lean
  TestsUtils/ExprGenerator.lean
  lakefile.lean
Labels: enhancement, ready, infra

#153 refactor to include variables with universe lists in `Ipld.Expr` representation
  .gitignore
  Yatima/Compiler/CompileM.lean
  Yatima/Compiler/Compiler.lean
  Yatima/Datatypes/Expr.lean
  Yatima/Ipld/ToIpld.lean
  lean_packages/manifest.json
Labels: wip, compiler

#159 Factoring out the converter to a proper mini-project
  Fixtures/Termination/Prelude.lean
  TestsUtils/CompileAndExtractTests.lean
  Yatima.lean
  Yatima/Converter/ConvertError.lean
  Yatima/Converter/ConvertM.lean
  Yatima/Converter/Converter.lean
  Yatima/Datatypes/Cid.lean
  Yatima/Datatypes/Const.lean
  Yatima/Datatypes/Expr.lean
  Yatima/Datatypes/Kind.lean
  Yatima/Datatypes/Name.lean
  Yatima/Datatypes/Store.lean
  Yatima/Ipld/ToIpld.lean
  Yatima/Transpiler/Test.lean
  Yatima/Transpiler/TranspileM.lean
  Yatima/Transpiler/Transpiler.lean
  Yatima/Typechecker/Typechecker.lean
Labels: enhancement

#162 Documentation
  TestsUtils/CompileAndExtractTests.lean
  Yatima.lean
  Yatima/Cli/CompileCmd.lean
  Yatima/Cli/PipeCmd.lean
  Yatima/Compiler/CompileM.lean
  Yatima/Compiler/Compiler.lean
  Yatima/Converter/ConvertError.lean
  Yatima/Converter/ConvertM.lean
  Yatima/Converter/Converter.lean
  Yatima/Datatypes/Cid.lean
  Yatima/Datatypes/Const.lean
  Yatima/Datatypes/Expr.lean
  Yatima/Datatypes/Kind.lean
  Yatima/Datatypes/Name.lean
  Yatima/Datatypes/Split.lean
  Yatima/Datatypes/Store.lean
  Yatima/Datatypes/Univ.lean
  Yatima/Ipld/ToIpld.lean
  Yatima/Transpiler/LurkFunctions.lean
  Yatima/Transpiler/Transpiler.lean
  Yatima/Transpiler/Utils.lean
Labels: documentation

#166 Documentation for the compiler
  TestsUtils/CompileAndExtractTests.lean
  Yatima/Cli/CompileCmd.lean
  Yatima/Cli/PipeCmd.lean
  Yatima/Compiler/CompileError.lean
  Yatima/Compiler/CompileM.lean
  Yatima/Compiler/Compiler.lean
  Yatima/Compiler/Printing.lean
  Yatima/Converter/Converter.lean
  Yatima/Datatypes/Expr.lean
  Yatima/Ipld/ToIpld.lean
  Yatima/Transpiler/Transpiler.lean
  Yatima/Transpiler/Utils.lean
  Yatima/Typechecker/Equal.lean
  Yatima/Typechecker/Eval.lean
  Yatima/Typechecker/Infer.lean
  Yatima/Typechecker/Printing.lean
  Yatima/Typechecker/Value.lean
Labels: documentation

#139 Testing the typechecker
  Fixtures/Typechecker/Reduction.lean
  Tests/Termination/NastyInductives.lean
  Tests/Termination/Prelude.lean
  Tests/Typechecker/Reduction.lean
  TestsUtils/CompileAndExtractTests.lean
  Yatima.lean
  Yatima/Cli/PipeCmd.lean
  Yatima/Compiler/Compiler.lean
  Yatima/Compiler/Printing.lean
  Yatima/Converter/Converter.lean
  Yatima/Datatypes/Expr.lean
  Yatima/Datatypes/Univ.lean
  Yatima/Ipld/ToIpld.lean
  Yatima/Transpiler/Transpiler.lean
  Yatima/Typechecker/Datatypes.lean
  Yatima/Typechecker/Equal.lean
  Yatima/Typechecker/Eval.lean
  Yatima/Typechecker/Infer.lean
  Yatima/Typechecker/Printing.lean
  Yatima/Typechecker/TypecheckError.lean
  Yatima/Typechecker/TypecheckM.lean
  Yatima/Typechecker/Typechecker.lean
  Yatima/Typechecker/Value.lean
  lakefile.lean
Labels: wip, typechecker, infra

#179 Document typechecker
  Yatima/Typechecker/Datatypes.lean
  Yatima/Typechecker/Equal.lean
  Yatima/Typechecker/Eval.lean
  Yatima/Typechecker/Infer.lean
  Yatima/Typechecker/Printing.lean
  Yatima/Typechecker/TypecheckError.lean
  Yatima/Typechecker/TypecheckM.lean
  Yatima/Typechecker/Typechecker.lean
Labels: documentation, ready

#177 Documentation for the converter
  Yatima/Compiler/Compiler.lean
  Yatima/Converter/ConvertError.lean
  Yatima/Converter/ConvertM.lean
  Yatima/Converter/Converter.lean
  Yatima/Typechecker/Eval.lean
Labels: documentation, ready

#161 add TDD test case for #160
  Fixtures/Roundtrip/Tricky.lean
  Tests/AnonCidGroups/Inductives.lean
  Tests/Roundtrip/Tricky.lean
  Yatima/Converter/ConvertM.lean
  Yatima/Converter/Converter.lean
  lakefile.lean
Labels: ready
